# Generated by Django 5.0.1 on 2024-01-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0003_auto_20200806_1144"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="rg",
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
